// Generated by CoffeeScript 1.6.3
(function() {
  var s_CloseNormal, s_CloseSelected, s_HelloWorld;

  s_HelloWorld = "images/HelloWorld.png";

  s_CloseNormal = "images/CloseNormal.png";

  s_CloseSelected = "images/CloseSelected.png";

  this.g_resources = [
    {
      src: s_HelloWorld
    }, {
      src: s_CloseNormal
    }, {
      src: s_CloseSelected
    }
  ];

}).call(this);
